// This file is auto-generated by generate_parse_tree_listener.py
// DO NOT EDIT

/*
 Copyright 2019 Alain Dargelas
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 *
 * File:   ParseTreeListener.cpp
 * Author: hs
 *
 */

#include <Surelog/Common/FileSystem.h>
#include <Surelog/Common/Session.h>
#include <Surelog/Design/VObject.h>
#include <Surelog/SourceCompile/ParseTreeListener.h>
#include <Surelog/SourceCompile/SymbolTable.h>

#include <algorithm>

namespace SURELOG {
VObjectType ParseTreeListener::getNodeType(const ParseTreeNode& node) const {
  return node ? node.m_object->m_type : VObjectType::sl_INVALID_;
}

ParseTreeNode ParseTreeListener::getRootNode() const {
  int32_t index = static_cast<int32_t>(m_count);
  while (--index >= 0) {
    if (m_objects[index].m_type == VObjectType::paTop_level_rule) {
      return ParseTreeNode(NodeId(index), &m_objects[index]);
    }
  }
  return ParseTreeNode();
}

bool ParseTreeListener::getNodeText(const ParseTreeNode& node,
                                    std::string& text) const {
  if (node && node.m_object->m_name) {
    text = m_session->getSymbolTable()->getSymbol(node.m_object->m_name);
    return true;
  }
  return false;
}

bool ParseTreeListener::getNodeText(const ParseTreeNode& node,
                                    std::string_view& text) const {
  if (node && node.m_object->m_name) {
    text = m_session->getSymbolTable()->getSymbol(node.m_object->m_name);
    return true;
  }
  return false;
}

bool ParseTreeListener::getNodeFileId(const ParseTreeNode& node,
                                      PathId& fileId) const {
  if (node) {
    fileId = node.m_object->m_fileId;
    return true;
  }
  return false;
}

bool ParseTreeListener::getNodeLocation(const ParseTreeNode& node,
                                        int32_t& startLine,
                                        int32_t& startColumn, int32_t& endLine,
                                        int32_t& endColumn) const {
  if (node) {
    startLine = node.m_object->m_line;
    startColumn = node.m_object->m_column;
    endLine = node.m_object->m_endLine;
    endColumn = node.m_object->m_endColumn;
    return true;
  }
  return false;
}

bool ParseTreeListener::getNodeStartLocation(const ParseTreeNode& node,
                                             int32_t& line,
                                             int32_t& column) const {
  int32_t endLine = 0, endColumn = 0;
  return getNodeLocation(node, line, column, endLine, endColumn);
}

bool ParseTreeListener::getNodeEndLocation(const ParseTreeNode& node,
                                           int32_t& line,
                                           int32_t& column) const {
  int32_t startLine = 0, startColumn = 0;
  return getNodeLocation(node, startLine, startColumn, line, column);
}

ParseTreeNode ParseTreeListener::getNodeParent(
    const ParseTreeNode& node) const {
  if (node && node.m_object->m_parent) {
    return ParseTreeNode(node.m_object->m_parent,
                         &m_objects[(RawNodeId)node.m_object->m_parent]);
  }
  return ParseTreeNode();
}

bool ParseTreeListener::getNodeChildren(
    const ParseTreeNode& node, parsetreenode_vector_t& children) const {
  if (!node) return false;
  if (!node.m_object->m_child) return true;

  for (NodeId id = node.m_object->m_child; id;
       id = m_objects[(RawNodeId)id].m_sibling) {
    children.emplace_back(id, &m_objects[(RawNodeId)id]);
  }

  return true;
}

ParseTreeNode ParseTreeListener::getNodePrevSibling(
    const ParseTreeNode& node) const {
  if (const ParseTreeNode parent = getNodeParent(node)) {
    parsetreenode_vector_t children;
    if (getNodeChildren(parent, children)) {
      for (size_t i = 1, ni = children.size(); i < ni; ++i) {
        if (children[i].m_index == node.m_index) {
          return children[i - 1];
        }
      }
    }
  }
  return ParseTreeNode();
}

ParseTreeNode ParseTreeListener::getNodeNextSibling(
    const ParseTreeNode& node) const {
  if (const ParseTreeNode parent = getNodeParent(node)) {
    parsetreenode_vector_t children;
    if (getNodeChildren(parent, children)) {
      for (size_t i = 0, ni = children.size() - 1; i < ni; ++i) {
        if (children[i].m_index == node.m_index) {
          return children[i + 1];
        }
      }
    }
  }
  return ParseTreeNode();
}

bool ParseTreeListener::getNodeSiblings(
    const ParseTreeNode& node, parsetreenode_vector_t& siblings) const {
  if (!node) return false;
  if (!node.m_object->m_parent) return true;

  const VObject& parent = m_objects[(RawNodeId)node.m_object->m_parent];

  for (NodeId id = parent.m_child; id;
       id = m_objects[(RawNodeId)id].m_sibling) {
    if (id != node.m_index) {
      siblings.emplace_back(id, &m_objects[(RawNodeId)id]);
    }
  }

  return true;
}

void ParseTreeListener::listen(Session* session, PathId fileId,
                               const VObject* objects, size_t count) {
  m_session = session;
  m_objects = objects;
  m_count = count;

  enterSourceFile(fileId);
  listen(getRootNode());
  leaveSourceFile(fileId);
}

void ParseTreeListener::listenChildren(const ParseTreeNode& node) {
  if (!node || !node.m_object->m_child) return;

  for (NodeId id = node.m_object->m_child; id;
       id = m_objects[(RawNodeId)id].m_sibling) {
    const ParseTreeNode childNode(id, &m_objects[(RawNodeId)id]);
    listen(childNode);
  }
}

void ParseTreeListener::listenSiblings(const ParseTreeNode& node) {
  if (!node || !node.m_object->m_parent) return;

  const VObject& parent = m_objects[(RawNodeId)node.m_object->m_parent];

  for (NodeId id = parent.m_child; id;
       id = m_objects[(RawNodeId)id].m_sibling) {
    if (id != node.m_index) {
      const ParseTreeNode siblingNode(id, &m_objects[(RawNodeId)id]);
      listen(siblingNode);
    }
  }
}

// clang-format off
<PRIVATE_LISTEN_IMPLEMENTATIONS>
// clang-format on

void ParseTreeListener::listen(const ParseTreeNode& node) {
  if (!m_visited.insert(node).second) {
    return;
  }

  m_callstack.emplace_back(node);

  // clang-format off
  switch (node.m_object->m_type) {
<LISTEN_CASE_STATEMENTS>
    default: break;
  };
  // clang-format on

  m_callstack.pop_back();
}
}  // namespace SURELOG
