// This file is auto-generated by generate_parser_listener.py
// DO NOT EDIT

/*
 Copyright 2019 Alain Dargelas
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 *
 * File:   AstListener.h
 * Author: hs
 *
 */

#ifndef SURELOG_ASTLISTENER_H
#define SURELOG_ASTLISTENER_H
#pragma once

#include <Surelog/Common/NodeId.h>
#include <Surelog/Common/PathId.h>
#include <Surelog/SourceCompile/VObjectTypes.h>

#include <cstdint>
#include <iterator>
#include <string>
#include <string_view>
#include <type_traits>
#include <unordered_set>
#include <vector>

// clang-format off
#define TRACE_INIT_CONTEXT                \
  int32_t sl = 0, sc = 0, el = 0, ec = 0; \
  std::string_view text;                  \
  getNodeLocation(node, sl, sc, el, ec);  \
  getNodeText(node, text)

#define TRACE_PRINT_CONTEXT \
  "(" << (NodeId)node << ") [" << sl << "," << sc <<  ":" << el << "," << ec <<  "], (" << escaped(text) << ")"

#define TRACE_ENTER TRACE_INIT_CONTEXT;       \
  m_strm << std::string(m_indent++ * 2, ' ')  \
  << __func__ << ": " << TRACE_PRINT_CONTEXT  \
  << std::endl
#define TRACE_LEAVE TRACE_INIT_CONTEXT;       \
  m_strm << std::string(2 * --m_indent, ' ')  \
  << __func__ << ": " << TRACE_PRINT_CONTEXT  \
  << std::endl
#define TRACE_VISIT TRACE_INIT_CONTEXT;       \
  m_strm << std::string(2 * m_indent, ' ')    \
  << __func__ << ": " << TRACE_PRINT_CONTEXT  \
  << std::endl
// clang-format on

namespace SURELOG {
class AstListener;
class Session;
class VObject;
struct AstNodeEqualityComparer;
struct AstNodeHash;
struct AstNodeLessComparer;

class AstNode final {
 public:
  AstNode() : m_index(), m_object(nullptr) {}
  AstNode(const AstNode& node) : m_index(node.m_index), m_object(node.m_object) {}
  AstNode(const NodeId& index, const VObject* const object) : m_index(index), m_object(object) {}

  AstNode& operator=(const AstNode& rhs) {
    if (this != &rhs) {
      m_index = rhs.m_index;
      m_object = rhs.m_object;
    }
    return *this;
  }

  bool operator==(const AstNode& rhs) const { return (m_index == rhs.m_index) && (m_object == rhs.m_object); }

  bool operator!=(const AstNode& rhs) const { return (m_index != rhs.m_index) || (m_object != rhs.m_object); }

 public:
  operator bool() const { return m_index && (m_object != nullptr); }
  operator NodeId() const { return m_index; }

 private:
  NodeId m_index;
  const VObject* m_object = nullptr;

  friend class AstListener;
  friend struct AstNodeHash;
  friend struct AstNodeEqualityComparer;
  friend struct AstNodeLessComparer;
};

struct AstNodeEqualityComparer final {
  bool operator()(const AstNode& lhs, const AstNode& rhs) const {
    return (lhs.m_index == rhs.m_index) && (lhs.m_object == rhs.m_object);
  }
};

struct AstNodeLessComparer final {
  bool operator()(const AstNode& lhs, const AstNode& rhs) const { return (lhs.m_index < rhs.m_index); }
};

struct AstNodeHash final {
  size_t operator()(const AstNode& node) const { return std::hash<RawNodeId>()(node.m_index); }
};

class AstNodeIterationHelper final {
 public:
  class Iterator final {
   public:
    using value_type = AstNode;
    using difference_type = std::ptrdiff_t;
    using pointer = const AstNode*;
    using reference = const AstNode&;
    using iterator_category = std::forward_iterator_tag;

    Iterator(const AstListener* listener) : m_listener(listener), m_node() {}
    Iterator(const AstListener* listener, const AstNode& node) : m_listener(listener), m_node(node) {}

    reference operator*() const { return m_node; }
    pointer operator->() const { return &m_node; }

    Iterator& operator++();
    Iterator operator++(int);

    friend bool operator==(const Iterator& a, const Iterator& b) {
      return (a.m_listener == b.m_listener) && (a.m_node == b.m_node);
    }
    friend bool operator!=(const Iterator& a, const Iterator& b) {
      return !((a.m_listener == b.m_listener) && (a.m_node == b.m_node));
    }

   private:
    const AstListener* const m_listener = nullptr;
    AstNode m_node;
  };

  AstNodeIterationHelper(const AstListener* listener, const AstNode& node) : m_listener(listener), m_node(node) {}
  ~AstNodeIterationHelper() = default;

  Iterator begin() { return Iterator(m_listener, m_node); }
  Iterator end() { return Iterator(m_listener); }

 private:
  const AstListener* const m_listener = nullptr;
  const AstNode m_node;
};

class AstListener {
 protected:
  using astnode_set_t = std::set<AstNode, AstNodeLessComparer>;
  using astnode_stack_t = std::vector<AstNode>;
  using astnode_vector_t = std::vector<AstNode>;

 public:
  AstListener() = default;
  AstListener(const AstListener& rhs);
  virtual ~AstListener() = default;

  virtual bool shouldWalkSourceFile(Session* session, PathId fileId) const { return true; }
  virtual void enterSourceFile(Session* session, PathId fileId, const std::string& sourceText);
  virtual void leaveSourceFile(PathId fileId, const std::string& sourceText) {}

  virtual void enter(const AstNode& node) {}
  virtual void leave(const AstNode& node) {}
  virtual void visit(const AstNode& node) {}

  // clang-format off
//<LISTENER_PUBLIC_ENTER_LEAVE_DECLARATIONS>
  // clang-format on

  // clang-format off
//<LISTENER_PUBLIC_VISIT_DECLARATIONS>
  // clang-format on

  template <typename T, typename... Args>
  T* fork(Args&&... args) {
    T* const listener = new T(args...);
    listener->m_session = m_session;
    listener->m_objects = m_objects;
    listener->m_count = m_count;
    return listener;
  }

  void listen(const AstNode& node);
  void listenChildren(const AstNode& node);
  void listenSiblings(const AstNode& node);

  void listen(Session* session, PathId fileId, const std::string& sourceText, const VObject* objects, size_t count);

  VObjectType getNodeType(const AstNode& node) const;
  AstNode getRootNode() const;

  bool getNodeText(const AstNode& node, std::string& text) const;
  bool getNodeText(const AstNode& node, std::string_view& text) const;
  bool getNodeFileId(const AstNode& node, PathId& fileId) const;

  bool getNodeStartLocation(const AstNode& node, int32_t& line, int32_t& column) const;
  bool getNodeEndLocation(const AstNode& node, int32_t& line, int32_t& column) const;
  bool getNodeLocation(const AstNode& node, int32_t& startLine, int32_t& startColumn, int32_t& endLine,
                       int32_t& endColumn) const;

  AstNode getNodeParent(const AstNode& node) const;
  AstNode getNodeParent(const AstNode& node, VObjectType type) const;
  AstNode getNodeParent(const AstNode& node, const std::set<VObjectType>& types) const;

  AstNode getNodePrevSibling(const AstNode& node) const;
  AstNode getNodePrevSibling(const AstNode& node, VObjectType type) const;
  AstNode getNodePrevSibling(const AstNode& node, const std::set<VObjectType>& types) const;

  AstNode getNodeNextSibling(const AstNode& node) const;
  AstNode getNodeNextSibling(const AstNode& node, VObjectType type) const;
  AstNode getNodeNextSibling(const AstNode& node, const std::set<VObjectType>& types) const;

  AstNode getNodeChild(const AstNode& node) const;
  AstNode getNodeChild(const AstNode& node, VObjectType type) const;
  AstNode getNodeChild(const AstNode& node, const std::set<VObjectType>& types) const;

  AstNodeIterationHelper getNodeChildren(const AstNode& node) const {
    return AstNodeIterationHelper(this, getNodeChild(node));
  }

  AstNodeIterationHelper getNodeSiblings(const AstNode& node) const {
    return AstNodeIterationHelper(this, getNodeNextSibling(node));
  }

  bool getNodeChildren(const AstNode& node, astnode_vector_t& children) const;
  bool getNodeSiblings(const AstNode& node, astnode_vector_t& siblings) const;

  AstNode getNodeOfTypeInTree(const AstNode& node, VObjectType type, size_t depth = 4) const;
  AstNode getNodeOfTypeInTree(const AstNode& node, const std::set<VObjectType>& types, size_t depth = 4) const;

  size_t getNodeChildCount(const AstNode& node) const;
  size_t getNodeChildCount(const AstNode& node, VObjectType type) const;
  size_t getNodeChildCount(const AstNode& node, const std::set<VObjectType>& types) const;

  size_t getNodeSiblingCount(const AstNode& node) const;
  size_t getNodeSiblingCount(const AstNode& node, VObjectType type) const;
  size_t getNodeSiblingCount(const AstNode& node, const std::set<VObjectType>& types) const;

  size_t getNodeCountInTree(const AstNode& node) const;
  size_t getNodeCountInTree(const AstNode& node, VObjectType type) const;
  size_t getNodeCountInTree(const AstNode& node, const std::set<VObjectType>& types) const;

  const NodeIdSet& getVisited() const { return m_visited; }
  size_t markVisited(const AstNode& node, bool includeSubTree);
  size_t clearVisited(const AstNode& node, bool includeSubTree);

  size_t markChildrenVisited(const AstNode& node, bool includeSubTree);
  size_t clearVisitedChildren(const AstNode& node, bool includeSubTree);

 private:
  size_t getNodeCountInTree(const NodeId& id) const;
  size_t getNodeCountInTree(const NodeId& id, VObjectType type) const;
  size_t getNodeCountInTree(const NodeId& id, const std::set<VObjectType>& types) const;

  size_t markVisited(const NodeId& id);
  size_t clearVisited(const NodeId& id);

 private:
  // clang-format off
//<LISTENER_PRIVATE_LISTEN_DECLARATIONS>
  // clang-format on

 protected:
  Session* m_session = nullptr;

 private:
  NodeIdSet m_visited;

  const VObject* m_objects = nullptr;
  size_t m_count = 0;
};

inline AstNodeIterationHelper::Iterator& AstNodeIterationHelper::Iterator::operator++() {
  m_node = m_listener->getNodeNextSibling(m_node);
  return *this;
}

inline AstNodeIterationHelper::Iterator AstNodeIterationHelper::Iterator::operator++(int) {
  Iterator tmp(m_listener, m_node);
  m_node = m_listener->getNodeNextSibling(m_node);
  return tmp;
}

class AstTraceListener final : public AstListener {
 public:
  explicit AstTraceListener(std::ostream& strm) : m_strm(strm), m_indent(0) {}
  ~AstTraceListener() final = default;

  void enterSourceFile(Session* session, SURELOG::PathId fileId, const std::string& sourceText) final;
  void leaveSourceFile(SURELOG::PathId fileId, const std::string& sourceText) final;

  std::string escaped(std::string_view str) const {
    std::string result;
    result.reserve(str.size() * 2);
    for (char ch : str) {
      if (ch == '\'')
        result.append("\\'");
      else if (ch == '\"')
        result.append("\\\"");
      else if (ch == '\\')
        result.append("\\");
      else if (ch == '\n')
        result.append("\\n");
      else if (ch == '\r')
        result.append("\\r");
      else if (ch == '\t')
        result.append("\\t");
      else
        result.append(1, ch);
    }
    return result;
  }

  // clang-format off
//<TRACER_ENTER_LEAVE_DECLARATIONS>
  // clang-format on

  // clang-format off
//<TRACER_VISIT_DECLARATIONS>
  // clang-format on

 private:
  std::ostream& m_strm;
  size_t m_indent = 0;
};
}  // namespace SURELOG

#undef TRACE_INIT_CONTEXT
#undef TRACE_PRINT_CONTEXT
#undef TRACE_ENTER
#undef TRACE_LEAVE
#undef TRACE_VISIT

#endif  // SURELOG_ASTLISTENER_H
